"""add is_pinned column to chat_sessions

Revision ID: 7dff0d28d157
Revises: f0fb63a71b0e
Create Date: 2026-07-17 09:30:09.097453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dff0d28d157'
down_revision: Union[str, None] = 'f0fb63a71b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
