"""add created_at to chat_messages

Revision ID: d5ae0ff7fc2a
Revises: c420c97ac729
Create Date: 2026-07-16 16:49:07.155552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ae0ff7fc2a'
down_revision: Union[str, None] = 'c420c97ac729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'created_at')
    # ### end Alembic commands ###
