"""add missing columns to chat_messages

Revision ID: f0fb63a71b0e
Revises: d5ae0ff7fc2a
Create Date: 2026-07-17 09:21:25.123309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0fb63a71b0e'
down_revision: Union[str, None] = 'd5ae0ff7fc2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('token_used', sa.Integer(), nullable=True, comment='消耗 Token 总量'))
    op.alter_column('chat_messages', 'tool_result',
               existing_type=sa.TEXT(),
               comment='工具调用返回结果',
               existing_comment='工具调用结果（JSON 格式，用于保存检测结果等）',
               existing_nullable=True)
    op.alter_column('chat_messages', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment='响应耗时 (毫秒)',
               existing_comment='推理耗时（毫秒）',
               existing_nullable=True)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.drop_column('chat_sessions', 'is_pinned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('is_pinned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='是否置顶'))
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.alter_column('chat_messages', 'latency_ms',
               existing_type=sa.INTEGER(),
               comment='推理耗时（毫秒）',
               existing_comment='响应耗时 (毫秒)',
               existing_nullable=True)
    op.alter_column('chat_messages', 'tool_result',
               existing_type=sa.TEXT(),
               comment='工具调用结果（JSON 格式，用于保存检测结果等）',
               existing_comment='工具调用返回结果',
               existing_nullable=True)
    op.drop_column('chat_messages', 'token_used')
    # ### end Alembic commands ###
